---
- hosts: all

  roles:
    - name: server_config
      become: yes
      become_user: root
      tags: configure

- hosts: wordpress

  roles:
    - name: php
      become: yes
      become_user: root
      tags: php
    - name: nginx
      become: yes
      become_user: root
      tags: nginx
